#version 460

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types : require

layout(local_size_x = 32) in;

shared int8_t shmem_a[512];
shared int8_t shmem_b[512];
shared int32_t shmem_out[256];

void main()
{
    coopmat<int8_t,  gl_ScopeSubgroup, 16, 16, gl_MatrixUseA>           A;
    coopmat<int8_t,  gl_ScopeSubgroup, 16, 16, gl_MatrixUseB>           B;
    coopmat<int32_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseAccumulator> C;
    C = coopmat<int32_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseAccumulator>(0);
    coopMatLoad(A, shmem_a, 0u, 32u, gl_CooperativeMatrixLayoutRowMajor);
    coopMatLoad(B, shmem_b, 0u, 32u, gl_CooperativeMatrixLayoutColumnMajor);
    C = coopMatMulAdd(A, B, C);
    coopMatStore(C, shmem_out, 0u, 16u, gl_CooperativeMatrixLayoutColumnMajor);
}
