#version 460

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types : require

void main()
{
    coopmat<int8_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> A;
    coopmat<int8_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseB> B;
    coopmat<int32_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseAccumulator> C;
    C = coopMatMulAdd(A, B, C);
}
